# Load data
```{r}
library("haven")
df_afro_kenya_2019 <- read_sav("afrobarometer_kenya.sav")  
df_afro_nigeria_2021 <- read_sav("afrobarometer_nigeria.sav")  
```

```{r}
library("haven")
library('dplyr')

chart3_data_kenya <- df_afro_kenya_2019 %>%
  mutate(
    age = ifelse(Q1!=998|999|-1, Q1, NA),
    is_christian = case_when(Q98A == 1|
                             Q98A == 2|
                             Q98A == 3|
                             Q98A == 4|
                             Q98A == 5|
                             Q98A == 6|
                             Q98A == 7|
                             Q98A == 8|
                             Q98A == 9|
                             Q98A == 10|
                             Q98A == 11|
                             Q98A == 12|
                             Q98A == 13|
                             Q98A == 14|
                             Q98A == 15|
                             Q98A == 16|
                             Q98A == 17 ~ 1,
                             Q98A == 0|
                             Q98A == 18|
                             Q98A == 19|
                             Q98A == 20|
                             Q98A == 21|
                             Q98A == 22|
                             Q98A == 23|
                             Q98A == 24|
                             Q98A == 25|
                             Q98A == 26|
                             Q98A == 27|
                             Q98A == 28|
                             Q98A == 29|
                             Q98A == 30|
                             Q98A == 31|
                             Q98A == 32|
                             Q98A == 33|
                             Q98A == 34|
                             Q98A == 300|
                             Q98A == 9995 ~ 0,
                             TRUE ~ NA_real_),
    completed_secondary_school = case_when(Q97 == 0|
                                           Q97 == 1|
                                           Q97 == 2|
                                           Q97 == 3|
                                           Q97 == 4 ~ 0,
                                           Q97 == 5|
                                           Q97 == 6|
                                           Q97 == 7|
                                           Q97 == 8|
                                           Q97 == 9 ~ 1,
                                           TRUE ~ NA_real_),
    has_job = case_when(Q95A == 0|
                        Q95A == 1 ~ 0,
                        Q95A == 2|
                        Q95A == 3 ~ 1,
                        TRUE ~ NA_real_),
    is_male = ifelse(THISINT==1, 1, 0),
    is_urban = case_when(Q115 == 1 ~ 0,
                         Q115 == 2 ~ 1,
                         TRUE ~ NA_real_),
    voted = case_when(Q13 == 0 ~ 0,
                      Q13 == 3 ~ 1,
                      TRUE ~ NA_real_),
    country = 'Kenya') %>%
  select(age, is_christian, completed_secondary_school, has_job, is_male, 
         is_urban, voted, country)

chart3_data_nigeria <- df_afro_nigeria_2021 %>%
  mutate(
    age = ifelse(Q1!=998|999|-1, Q1, NA),
    is_christian = case_when(Q98A == 1|
                             Q98A == 2|
                             Q98A == 3|
                             Q98A == 4|
                             Q98A == 5|
                             Q98A == 6|
                             Q98A == 7|
                             Q98A == 8|
                             Q98A == 9|
                             Q98A == 10|
                             Q98A == 11|
                             Q98A == 12|
                             Q98A == 13|
                             Q98A == 14|
                             Q98A == 15|
                             Q98A == 16|
                             Q98A == 17 ~ 1,
                             Q98A == 0|
                             Q98A == 18|
                             Q98A == 19|
                             Q98A == 20|
                             Q98A == 21|
                             Q98A == 22|
                             Q98A == 23|
                             Q98A == 24|
                             Q98A == 25|
                             Q98A == 26|
                             Q98A == 27|
                             Q98A == 28|
                             Q98A == 29|
                             Q98A == 30|
                             Q98A == 31|
                             Q98A == 32|
                             Q98A == 33|
                             Q98A == 34|
                             Q98A == 300|
                             Q98A == 9995 ~ 0,
                             TRUE ~ NA_real_),
    completed_secondary_school = case_when(Q97 == 0|
                                           Q97 == 1|
                                           Q97 == 2|
                                           Q97 == 3|
                                           Q97 == 4 ~ 0,
                                           Q97 == 5|
                                           Q97 == 6|
                                           Q97 == 7|
                                           Q97 == 8|
                                           Q97 == 9 ~ 1,
                                           TRUE ~ NA_real_),
    has_job = case_when(Q95A == 0|
                        Q95A == 1 ~ 0,
                        Q95A == 2|
                        Q95A == 3 ~ 1,
                        TRUE ~ NA_real_),
    is_male = ifelse(THISINT==1, 1, 0),
    is_urban = case_when(Q115 == 1 ~ 0,
                         Q115 == 2 ~ 1,
                         TRUE ~ NA_real_),
    voted = case_when(Q13 == 0 ~ 0,
                      Q13 == 3 ~ 1,
                      TRUE ~ NA_real_),
    country = 'Nigeria') %>%
  select(age, is_christian, completed_secondary_school, has_job, is_male, 
         is_urban, voted, country)

chart3_data <- rbind(chart3_data_kenya, chart3_data_nigeria)

chart3_data <- chart3_data %>%
  group_by(country) %>%
  summarise(avg_age = mean(age, na.rm=TRUE),
            is_christian = mean(is_christian, na.rm=TRUE), 
            pct_completed_secondary_school = mean(completed_secondary_school, 
                                                  na.rm=TRUE), 
            pct_has_job = mean(has_job, na.rm=TRUE), 
            pct_male = mean(is_male, na.rm=TRUE), 
            pct_urban  = mean(is_urban, na.rm=TRUE), 
            pct_voted = mean(voted, na.rm=TRUE))

write.csv(chart3_data,"chart3_data.csv", row.names = FALSE)
```


# Clean Data
```{r}
library('dplyr')

chart1_data <- df %>%
  mutate(count = 1, date = anytime::anydate(Date)) %>%
  group_by(date = lubridate::floor_date(date, 'month')) %>%
  summarise(value = sum(count)) %>%
  select(value, date)

write.csv(chart1_data,"a3cleanedonly2015_chart1.csv", row.names = FALSE, quote=FALSE)

chart2_data <- df %>%
  mutate(shot = ifelse(Armed == "Gun", 1, 0), count = 1, state = State) %>%
  group_by(state) %>%
  summarise(percent_armed_gun = round(sum(shot) / sum(count) * 100, digits=2)) %>%
  select(state, percent_armed_gun)

write.csv(chart2_data,"a3cleanedonly2015_chart2.csv", row.names = FALSE, quote=FALSE)

chart3_data <- df %>%
  mutate(count = 1, race = Race) %>%
  filter(race!='') %>%
  group_by(race) %>%
  summarise(percent_race = round(sum(count) / nrow(df), digits=2)) %>%
  select(race, percent_race)

write.csv(chart3_data,"a3cleanedonly2015_chart3.csv", row.names = FALSE, quote=FALSE)
```